In [62]:
import pandas as pd

In [63]:

df = pd.read_csv('../data/spotify-tracks.csv',index_col=0)
df.head()

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,1,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,1,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,0,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,0,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,2,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [64]:
df.dropna(inplace=True)

In [65]:
df.isnull().sum()

track_id            0
artists             0
album_name          0
track_name          0
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [66]:
df1 = pd.read_csv('../data/kworb_spotify_global_totals.csv')

In [67]:
df1.isnull().sum()

Artist and Title        0
Days                    0
T10                 10143
Pk                      0
(x?)                10791
PkStreams               0
Total                   0
dtype: int64

In [68]:
df1['(x?)'].fillna(1, inplace=True)

C:\Users\Anabel\AppData\Local\Temp\ipykernel_15144\1364403238.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['(x?)'].fillna(1, inplace=True)

In [69]:
def aux(x):
    try:
        return int(x)
    except:
        return int(str(x).replace("(x",'').replace(')','').strip())
    

df1['(x?)'] = df1['(x?)'].apply(aux)

In [70]:
df1

,Artist and Title,Days,T10,Pk,(x?),PkStreams,Total
0,The Weeknd-Blinding Lights,2040,446.0,1,82,"8,453,567","4,821,495,064"
1,Harry Styles-As It Was,1181,426.0,1,81,"16,103,849","3,881,679,744"
2,Ed Sheeran-Shape of You,2560,237.0,1,98,"9,878,194","3,840,683,196"
3,Lewis Capaldi-Someone You Loved,2247,107.0,4,1,"3,974,554","3,726,017,096"
4,Post Malone-Sunflower - Spider-Man: Into the S...,2243,213.0,1,16,"5,033,261","3,532,117,592"
...,...,...,...,...,...,...,...
11193,Wisin-Adrenalina,1,NaN,188,1,"124,862","124,862"
11194,Iggy Azalea-Work,1,NaN,196,1,"120,954","120,954"
11195,Orup-Främling,1,NaN,199,1,"120,760","120,760"
11196,Ed Sheeran-Nina,1,NaN,199,1,"120,515","120,515"
11197,Take That-These Days,1,NaN,198,1,"115,382","115,382"

In [71]:
def clean_number(x):
    return int(str(x).replace(",", '').strip())

df1['PkStreams'] = df1['PkStreams'].apply(clean_number)
df1['Total'] = df1['Total'].apply(clean_number)

In [72]:
df1['artist'] = df1['Artist and Title'].apply(lambda x: x.split('-')[0])
df1['songs'] = df1['Artist and Title'].apply(lambda x: ' '.join(x.split('-')[1:]))

In [109]:
df1

,Artist and Title,Days,T10,Pk,(x?),PkStreams,Total,artist,songs
0,The Weeknd-Blinding Lights,2040,446.0,1,82,8453567,4821495064,The Weeknd,Blinding Lights
1,Harry Styles-As It Was,1181,426.0,1,81,16103849,3881679744,Harry Styles,As It Was
2,Ed Sheeran-Shape of You,2560,237.0,1,98,9878194,3840683196,Ed Sheeran,Shape of You
3,Lewis Capaldi-Someone You Loved,2247,107.0,4,1,3974554,3726017096,Lewis Capaldi,Someone You Loved
4,Post Malone-Sunflower - Spider-Man: Into the S...,2243,213.0,1,16,5033261,3532117592,Post Malone,Sunflower Spider Man: Into the Spider Verse
...,...,...,...,...,...,...,...,...,...
11193,Wisin-Adrenalina,1,NaN,188,1,124862,124862,Wisin,Adrenalina
11194,Iggy Azalea-Work,1,NaN,196,1,120954,120954,Iggy Azalea,Work
11195,Orup-Främling,1,NaN,199,1,120760,120760,Orup,Främling
11196,Ed Sheeran-Nina,1,NaN,199,1,120515,120515,Ed Sheeran,Nina
11197,Take That-These Days,1,NaN,198,1,115382,115382,Take That,These Days

In [96]:
df1['songs']

0                                      Blinding Lights
1                                            As It Was
2                                         Shape of You
3                                    Someone You Loved
4        Sunflower   Spider Man: Into the Spider Verse
                             ...
11193                                       Adrenalina
11194                                             Work
11195                                         Främling
11196                                             Nina
11197                                       These Days
Name: songs, Length: 11198, dtype: object

In [122]:
len(df['artists'].unique())

31437

In [132]:
df = df.drop_duplicates(subset=['track_id']).reset_index()

In [138]:
a=set()
for i in df['artists'].unique():
    if i.strip() in df1['artist'].values:
        a.add(i)

In [139]:
len(a)

771

In [140]:
len(df['artists'].unique())

31437

In [141]:
a

{'2Pac',
 '347aidan',
 '5 Seconds of Summer',
 '50 Cent',
 '6ix9ine',
 'A Great Big World',
 'A R I Z O N A',
 'A Tribe Called Quest',
 'ABBA',
 'AC/DC',
 'AJR',
 'AP Dhillon',
 'ATB',
 'AURORA',
 'Aaron Smith',
 'Abraham Mateo',
 'Adele',
 'Adolphson & Falk',
 'Aerosmith',
 'Aitana',
 'Akon',
 'Alabama Shakes',
 'Alan Walker',
 'Aldair Playboy',
 'Alec Benjamin',
 'Alejandro Fernández',
 'Alejandro Sanz',
 'Alessia Cara',
 'Alesso',
 'Ali Gatie',
 'Alicia Keys',
 'Alle Farben',
 'Allyawan',
 'Aloe Blacc',
 'Alonzo',
 'Alphaville',
 'Alvaro Diaz',
 'Alvaro Soler',
 'Amanda Jenssen',
 'American Authors',
 'Amy Winehouse',
 'Andrew Gold',
 'Andy Grammer',
 'Anirudh Ravichander',
 'Anitta',
 'Annie Lennox',
 'Ant Saunders',
 'Anuel AA',
 'Anuv Jain',
 'Arctic Monkeys',
 'Aretha Franklin',
 'Ariana Grande',
 'Arijit Singh',
 'Armani White',
 'Armin van Buuren',
 'Ashe',
 'Ashnikko',
 'Astrid S',
 'Audien',
 'Audioslave',
 'Ava Max',
 'Avicii',
 'Avine Vinny',
 'Axwell /\\ Ingrosso',
 'B.B. King',
 'BANKS',
 'BANNERS',
 'BIGBANG',
 'BLACKPINK',
 'BTS',
 'Baby Tate',
 'Backstreet Boys',
 'Bad Bunny',
 'Bad Gyal',
 'Bag Raiders',
 'Bastille',
 'Bazzi',
 'Bea Miller',
 'Beach Bunny',
 'Beach House',
 'Beach Weather',
 'Bebe Rexha',
 'Becky G',
 'Becky Hill',
 'Bee Gees',
 'Bella Poarch',
 'Ben E. King',
 'Ben Howard',
 'Benjamin Ingrosso',
 'Benson Boone',
 'Beyoncé',
 'Bill Withers',
 'Billie Eilish',
 'Billy Joel',
 'Black Eyed Peas',
 'Blackstreet',
 'Bleachers',
 'Blind Channel',
 'Blood Orange',
 'Blue Öyster Cult',
 'Bob Marley & The Wailers',
 'Bomba Estéreo',
 'Bon Iver',
 'Boney M.',
 'Bonnie Tyler',
 'Boomdabash',
 'Boza',
 'Brenda Lee',
 'Brett Eldredge',
 'Bring Me The Horizon',
 'Brisa Star',
 'Britney Spears',
 'Bruce Springsteen',
 'Bruno Mars',
 'Bryan Adams',
 'Bryce Vine',
 'Burna Boy',
 'Busta Rhymes',
 'BØRNS',
 'CHVRCHES',
 'CNCO',
 'CRO',
 'Cali Y El Dandee',
 'Calvin Harris',
 'Camila Cabello',
 'Camilo',
 'Capital Cities',
 'Cardi B',
 'Carly Rae Jepsen',
 'Carrie Underwood',
 'Charlie Puth',
 'Charly Black',
 'Chino & Nacho',
 'Chris Brown',
 'Chris Cornell',
 'Chris Rea',
 'Chris Stapleton',
 'Christina Perri',
 'Chuck Berry',
 'Cigarettes After Sex',
 'Clairo',
 'Clayton & Romário',
 'Clean Bandit',
 'Cliff Richard',
 'Clinton Kane',
 'Clyde McPhatter',
 'Coldplay',
 'Conan Gray',
 'Connie Francis',
 'Coolio',
 'Cosculluela',
 'Craig David',
 'Creedence Clearwater Revival',
 'Creepy Nuts',
 'Crush',
 'Cults',
 'Cyndi Lauper',
 'Cynthia Erivo',
 'DIVINE',
 'DJ Snake',
 'DMX',
 'DaBaby',
 'Daddy Yankee',
 'Damso',
 'Dan + Shay',
 'Danna Paola',
 'Danny Ocean',
 'Darshan Raval',
 'Daryl Hall & John Oates',
 'David Guetta',
 'David Kushner',
 'Daya',
 'De La Ghetto',
 'De Vet Du',
 'Dean Martin',
 'Demi Lovato',
 'Deorro',
 'Dermot Kennedy',
 'Devin Dawson',
 'Dido',
 'Diego & Victor Hugo',
 'Dillon Francis',
 'Dilsinho',
 'Dimitri Vegas & Like Mike',
 'Disclosure',
 'Disturbed',
 'Doja Cat',
 'Dolly Parton',
 'Dominic Fike',
 'Don Omar',
 'Donny Hathaway',
 'Doris Day',
 'Douglas & Vinicius',
 'Drake',
 'Dream',
 'Dua Lipa',
 'Duke Dumont',
 'Duncan Laurence',
 'ENHYPEN',
 'EXO',
 'Eagles',
 'Earth, Wind & Fire',
 'Eartha Kitt',
 'Echosmith',
 'Ed Sheeran',
 'Ella Fitzgerald',
 'Ella Henderson',
 'Elle King',
 'Elley Duhé',
 'Ellie Goulding',
 'Elton John',
 'Elvis Presley',
 'Em Beihold',
 'Emeli Sandé',
 'Eminem',
 'Emir Can İğrek',
 'Eno',
 'Enrique Iglesias',
 'Eric Clapton',
 'Eric Land',
 'Evanescence',
 'Ezhel',
 'FKA twigs',
 'FLETCHER',
 'Fall Out Boy',
 'Farid Bang',
 'Farruko',
 'Feder',
 'Feid',
 'Felipe Araújo',
 'Felix Jaehn',
 'Fernando & Sorocaba',
 'Fetty Wap',
 'Fifth Harmony',
 'Fireboy DML',
 'Fleetwood Mac',
 'Flo Rida',
 'Florence + The Machine',
 'Florida Georgia Line',
 'Foals',
 'Foo Fighters',
 'Foster The People',
 'Fousheé',
 'Frank Ocean',
 'Fuego',
 'Fujii Kaze',
 'Future',
 'GASHI',
 'GAYLE',
 'Gabriel Diniz',
 'Galantis',
 'Gambi',
 'Gaullin',
 'George Ezra',
 'George Henrique & Rodrigo',
 'Gesaffelstein',
 'Ghost',
 'Glass Animals',
 'Glee Cast',
 'Gorillaz',
 'Gracie Abrams',
 'Green Day',
 'Guaynaa',
 'Guilherme & Benuto',
 'Gunna',
 "Guns N' Roses",
 'Gustavo Mioto',
 'Gusttavo Lima',
 'HRVY',
 'HUGEL',
 'HVME',
 'Halsey',
 'Hanumankind',
 'Hardwell',
 'Harry Nach',
 'Harry Styles',
 'Hasse Andersson',
 'Hayley Kiyoko',
 'Hayley Williams',
 'Henrique & Juliano',
 'Henry Freitas',
 'Hippie Sabotage',
 'Hozier',
 'Humberto & Ronaldo',
 'Hunter Hayes',
 'Håkan Hellström',
 'ILLENIUM',
 'ITZY',
 'IU',
 'IVE',
 'Icona Pop',
 'Idina Menzel',
 'Iggy Pop',
 'Il Volo',
 'Imagine Dragons',
 'Israel & Rodolffo',
 'Ivete Sangalo',
 'J Balvin',
 'J. Cole',
 'JENNIE',
 'JEON SOMI',
 'JP Cooper',
 'JVKE',
 'Jack Harlow',
 'Jain',
 'Jake Owen',
 'Jakob Karlberg',
 'James Arthur',
 'James Blake',
 'James Blunt',
 'James Brown',
 'James Hype',
 'Jamie Miller',
 'Jamie xx',
 'Janelle Monáe',
 'Jarabe De Palo',
 'Jasleen Royal',
 'Jason Aldean',
 'Jason Derulo',
 'Jason Mraz',
 'Jay Sean',
 'Jaymes Young',
 'Jennifer Lopez',
 'Jeremy Zucker',
 'Jerry Di',
 'Jess Glynne',
 'Jesse & Joy',
 'Jessi',
 'Jessie Ware',
 'Jimmy Buffett',
 'Joe Cocker',
 'Joel Adams',
 'Joey Montana',
 'John Denver',
 'John Legend',
 'John Lennon',
 'John Mayer',
 'Johnny Cash',
 'Joji',
 'Jonas Brothers',
 'Jorge & Mateus',
 'Journey',
 'João Gustavo e Murilo',
 'Juan Magán',
 'Juanes',
 'Jubin Nautiyal',
 'Judy Garland',
 'Julia Michaels',
 'Justin Bieber',
 'KAI',
 'KALEO',
 'KAROL G',
 'KONGOS',
 'Kacey Musgraves',
 'Kane Brown',
 'Karan Aujla',
 'Kate Bush',
 'Katy Perry',
 'KayBlack',
 'Keane',
 'Kehlani',
 'Keith Urban',
 'Kelsea Ballerini',
 'Kendrick Lamar',
 'Kenny Rogers',
 'Kenshi Yonezu',
 'Kep1er',
 'Kid Cudi',
 'Kiiara',
 'Kim Petras',
 'Kina',
 'King',
 'King Princess',
 'Kodak Black',
 'Koe Wetzel',
 'Kontra K',
 'Krewella',
 'Kungs',
 'Kylie Minogue',
 'LE SSERAFIM',
 'LISA',
 'LIT killah',
 'LUDMILLA',
 'La Adictiva',
 'La Oreja de Van Gogh',
 'Labrinth',
 'Lady Gaga',
 'Lana Del Rey',
 'Lasso',
 'Lauana Prado',
 'Laufey',
 'Lauren Daigle',
 'Lauren Spencer Smith',
 'Lauv',
 'Lavern',
 'LeeHi',
 'Lele Pons',
 'Leon Bridges',
 'Leona Lewis',
 'Leonard Cohen',
 'Leslie Grace',
 'Lewis Capaldi',
 'Lil Baby',
 'Lil Dicky',
 'Lil Nas X',
 'Lil Peep',
 'Lil Pump',
 'Lil Tjay',
 'Lil Xan',
 'Lilly Wood and The Prick',
 'Linkin Park',
 'Lithe',
 'Little Big Town',
 'Little Mix',
 'Lizzo',
 'Lola Indigo',
 'Lord Huron',
 'Loreen',
 'Loren Allred',
 'Lost Frequencies',
 'Louane',
 'Louis Armstrong',
 'Luan Pereira',
 'Luar La L',
 'Luciano',
 'Lucky Daye',
 'Luis Fonsi',
 'Luke Bryan',
 'Luke Combs',
 'Lynyrd Skynyrd',
 'M.I.A.',
 'M83',
 'MAGIC!',
 'MARINA',
 'MAX',
 'MC Cebezinho',
 'MC Fioti',
 'MC Kevin o Chris',
 'MC Kevinho',
 'MC Levin',
 'MKTO',
 'Mabel',
 'Mac DeMarco',
 'Mac Miller',
 'Madison Beer',
 'Madonna',
 'Maggie Rogers',
 'Maiara & Maraisa',
 'Majestic',
 'Majid Jordan',
 'Maluma',
 'Manan Bhardwaj',
 'Manu Gavassi',
 'Manuel Turizo',
 'Marc Anthony',
 'Marc Seguí',
 'Maren Morris',
 'Marilyn Manson',
 'Maroon 5',
 'Marshmello',
 'Martin Garrix',
 'Martin Jensen',
 'Marvin Gaye',
 'Mary J. Blige',
 'Masked Wolf',
 'Matheus & Kauan',
 'Matt Maltese',
 'Mc Davi',
 'Mc Don Juan',
 'Mc IG',
 'Megan Moroney',
 'Mel & Kim',
 'Mel Tormé',
 'Melanie Martinez',
 'Melendi',
 'Metallica',
 'Michael Bublé',
 'Michael Jackson',
 'Michael Schulte',
 'Miike Snow',
 'Mike Perry',
 'Mike Posner',
 'Miley Cyrus',
 'Milky Chance',
 'Mimi Webb',
 'MisterWives',
 'Mitraz',
 'Mitski',
 'Mobb Deep',
 'Montez',
 'Morat',
 'Morgan Wallen',
 'Mother Mother',
 'Motörhead',
 'Mr Eazi',
 'Mumford & Sons',
 'Muni Long',
 'Musical Youth',
 'My Chemical Romance',
 'Myke Towers',
 'Márcia Fellipe',
 'Måneskin',
 'N.W.A.',
 'NCT DREAM',
 'NF',
 'NMIXX',
 'Nacho',
 'Nas',
 'Nat King Cole',
 'Nat King Cole Trio',
 'Neil Diamond',
 'Nelly Furtado',
 'Nessa Barrett',
 'New West',
 'Niall Horan',
 'Nickelback',
 'Nicki Minaj',
 'Nicky Jam',
 'Nicky Romero',
 'Nina Nesbitt',
 'Ninho',
 'Nirvana',
 'Niska',
 'Norah Jones',
 'Norlie & KKV',
 'Norm Ender',
 'Oasis',
 'Of Monsters and Men',
 'Oliver Tree',
 'Olivia Dean',
 'Olivia Rodrigo',
 'Omah Lay',
 'Omar Apollo',
 'One Direction',
 'OneRepublic',
 'Orup',
 'Os Barões Da Pisadinha',
 'Otis Redding',
 'Otto Knows',
 'Owl City',
 'Ozuna',
 'Ozzy Osbourne',
 'PNL',
 'PSY',
 'PUBLIC',
 'Paloma Faith',
 'Pamungkas',
 'Panic! At The Disco',
 'Paramore',
 'Parangolé',
 'Passenger',
 'Paul Anka',
 'Paul McCartney',
 'Paulo Pires',
 'Peggy Lee',
 'Perry Como',
 'Philip George',
 'Pink Floyd',
 'Pink Sweat$',
 'Playboi Carti',
 'Popcaan',
 'Porter Robinson',
 'Powfu',
 'Pretenders',
 'Prince',
 'Pritam',
 'Purple Disco Machine',
 'Quavo',
 'Queen',
 'R3HAB',
 'ROSÉ',
 'Rachel Platten',
 'Radiohead',
 "Rag'n'Bone Man",
 'Raghav Chaitanya',
 'Ram Sampath',
 'Ramin Djawadi',
 'Rammstein',
 'Rauw Alejandro',
 'Ravyn Lenae',
 'Ray Parker Jr.',
 'Raí Saia Rodada',
 'Red Hot Chili Peppers',
 'Red Velvet',
 'Regard',
 'Rels B',
 'Rick James',
 'Ricky Martin',
 'Ricky Montgomery',
 'Rita Ora',
 'Ritt Momney',
 'Rixton',
 'Roar',
 'Robin Schulz',
 'Robyn',
 'Route 94',
 'Run–D.M.C.',
 'Ruth B.',
 'Röyksopp',
 'SAINt JHN',
 'SCH',
 'SEVENTEEN',
 'Sabrina Carpenter',
 'Sam Hunt',
 'Sam Smith',
 'San Holo',
 'Sara Kays',
 'Sarah Connor',
 'Sarah Cothran',
 'Seafret',
 'Sean Paul',
 'Sebastian Yatra',
 'Seinabo Sey',
 'Selena Gomez',
 'Sevyn Streeter',
 'Shaggy',
 "Shakin' Stevens",
 'Shakira',
 'Shawn Mendes',
 'Sheppard',
 'Shouse',
 'Shubh',
 'SiM',
 'Sia',
 'Sidhu Moose Wala',
 'Sigala',
 'Sigma',
 "Sinéad O'Connor",
 'Skylar Grey',
 'Sleepy Hallow',
 'Slipknot',
 'Snoop Dogg',
 'Snow Patrol',
 'Soundgarden',
 'Starley',
 'State of Sound',
 'Stephen Sanchez',
 'Stevie Wonder',
 'Stray Kids',
 'Stromae',
 'Sub Urban',
 'Suki Waterhouse',
 'Surf Curse',
 'Surfaces',
 'Swedish House Mafia',
 'System Of A Down',
 'TINI',
 'TOMORROW X TOGETHER',
 'TOOL',
 'TOTO',
 'TV Girl',
 'TWICE',
 'Tai Verdes',
 'Talking Heads',
 'Tarkan',
 'Tate McRae',
 'Taylor Swift',
 'Tayrone',
 'Tears For Fears',
 'Thalia',
 'The 1975',
 'The Avener',
 'The Beach Boys',
 'The Beatles',
 'The Black Keys',
 'The Chainsmokers',
 'The Clash',
 'The Cranberries',
 'The Drifters',
 'The Fray',
 'The Goo Goo Dolls',
 'The Jackson 5',
 'The Kid LAROI',
 'The Killers',
 'The Lumineers',
 'The Marías',
 'The Moonglows',
 'The National',
 'The Neighbourhood',
 'The Outfield',
 'The Platters',
 'The Police',
 'The Rare Occasions',
 'The Rolling Stones',
 'The Script',
 'The Strokes',
 'The Strumbellas',
 'The Vamps',
 'The Walters',
 'The Weeknd',
 'The White Stripes',
 'The Wombats',
 'The xx',
 'Thirty Seconds To Mars',
 'Thomas Gold',
 'Thomas Jack',
 'Thomas Rhett',
 'Timeflies',
 'Tina Turner',
 'Tiësto',
 'Toby Keith',
 'Tom Odell',
 'Tom Petty',
 'Tom Petty and the Heartbreakers',
 'Tom Walker',
 'Tony Bennett',
 'Tove Lo',
 'Tove Styrke',
 'Tracy Chapman',
 'Train',
 'Travis Scott',
 'Trevor Daniel',
 'Tritonal',
 'Troye Sivan',
 'Tulus',
 'Tungevaag',
 'Twenty One Pilots',
 'Ty Dolla $ign',
 'UMI',
 'UZI',
 'Ufo361',
 'Us The Duo',
 'Vampire Weekend',
 'Van Halen',
 'Van Morrison',
 'Vance Joy',
 'Vegedream',
 'Vicetone',
 'Vigiland',
 'Vince Guaraldi Trio',
 'Vishal Mishra',
 'Vundabar',
 'WALK THE MOON',
 'WILLOW',
 'Walker Hayes',
 'Wallows',
 'Wesley Safadão',
 'Wham!',
 "Why Don't We",
 'Wiktoria',
 'Wilbur Soot',
 'Wisin & Yandel',
 'Wiz Khalifa',
 'Wizkid',
 'X Ambassadors',
 'XXXTENTACION',
 'YOASOBI',
 'YUNGBLUD',
 'Yellow Claw',
 'Young Thug',
 'Yung Gravy',
 'ZAYN',
 'ZICO',
 'Zach Bryan',
 'Zara Larsson',
 'Zedd',
 'Zeynep Bastık',
 'Zion & Lennox',
 'Zoe Wees',
 'Zé Vaqueiro',
 'aespa',
 'beabadoobee',
 'blackbear',
 'carolesdaughter',
 'dvsn',
 'girl in red',
 'grandson',
 'salem ilese',
 'twocolors',
 'Ícaro e Gilmar',
 'Şanışer'}

In [153]:
mapeo= {}
for i,j in enumerate(df1['artist'].values):
    if j in a:
        mapeo[f'{j}_{i}']=i

len(mapeo)

8806